color: null
fieldLayouts:
  533ce778-ca99-4ee3-a6a1-ccd6612ff3e5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-06-06T11:57:01+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7251db82-f938-4718-bd39-a89e0b4313bb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-06T11:59:35+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 0236b792-3d9d-4357-bfb5-27f0563387ba # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cf32fa10-c527-4611-aacb-b3fbd1562d0b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-06T11:59:35+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: bc050c68-33ca-41b4-ba7f-cd9d257a2a8d # About
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3c973705-2c97-4040-8049-324804e0ad3c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1673053c-90c5-456a-9c5d-9e7e0c1b3e59
        userCondition: null
handle: carrousel
hasTitleField: true
icon: null
name: Carrousel
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
