color: null
fieldLayouts:
  e3bfed2d-0548-4ad8-81aa-53ac32c86613:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-16T09:43:11+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4b289d09-acdc-476f-8cae-0439b6a47bb4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-13T08:20:41+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 0236b792-3d9d-4357-bfb5-27f0563387ba # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 96d65d6c-a75a-45f2-b513-7430c08c3a4c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-16T11:41:40+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: dda661cb-3856-4b1b-b3ed-ad85be204bdb # Navigation Link URL
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b7aa9ede-b9d5-47ea-bafc-0dbb43f68005
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 10a16acb-6fca-4d41-8c42-8763699e0e6b
        userCondition: null
handle: footer
hasTitleField: true
icon: null
name: Footer
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
