color: null
fieldLayouts:
  bcbad39e-e6f7-4c40-abaf-20a1cc631731:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-16T08:41:12+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e2fc9e89-eb6c-4bb9-a41c-9c8bdc581aca
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-16T08:45:23+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: dda661cb-3856-4b1b-b3ed-ad85be204bdb # Navigation Link URL
            handle: LinkUrl
            includeInCards: false
            instructions: null
            label: LinkUrl
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 641ade0f-0bb6-43ef-9eb9-00f9c0d0840b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8b9ee9a7-4f79-4c82-a10c-037797ac4ab7
        userCondition: null
handle: navigationLinkUrl
hasTitleField: true
icon: link
name: 'Navigation Link URL'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
