color: null
fieldLayouts:
  d9a9d27e-e58f-489a-b3bf-fa684102ef4c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-23T13:18:33+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e4f1826b-19a0-49d4-ac54-dd691e1de88c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-23T13:20:14+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 0236b792-3d9d-4357-bfb5-27f0563387ba # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 659c3a72-7975-466f-bb38-6c2d98a4e5e5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: eedbabca-b440-483c-8888-a700418fcc99
        userCondition: null
handle: navigationLogo
hasTitleField: true
icon: null
name: 'Navigation Logo'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
