altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  585a7448-74c2-4928-89f9-f7321b0a66aa:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-23T12:34:49+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: a1bacd90-dcd7-4441-a2f4-9125be4a6fd8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-23T12:37:42+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 0236b792-3d9d-4357-bfb5-27f0563387ba # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6e6dadcd-3916-43fc-bc27-f37af4ad60b6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c0eb28a2-c095-4d4c-9b63-5cc1a15db3a9
        userCondition: null
fs: assets
handle: images
name: Images
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
