defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 9287a8ba-2efe-4afe-80f7-c18df9cf40f1 # about
handle: about
maxAuthors: 1
name: about
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  28873fc0-5092-43dc-94ff-c29ce0463c2c: # Sint Coleta
    enabledByDefault: false
    hasUrls: true
    template: about/_entry.twig
    uriFormat: 'about/{slug}'
  cbe9e6f0-0c8d-485f-b0d9-499af8215148: # Mariahuis
    enabledByDefault: true
    hasUrls: true
    template: _layouts/about.twig
    uriFormat: 'about/{slug}'
  f2fcfcef-2e85-4ee2-94c7-b1ce5abab2ac: # Cultuur Colette
    enabledByDefault: false
    hasUrls: true
    template: about/_entry.twig
    uriFormat: 'about/{slug}'
structure:
  maxLevels: null
  uid: 263c78e3-9435-4c39-b728-372c2767f6d9
type: structure
