defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 2f9a9735-87e9-4eec-96e1-d24d98a3dd96 # Carrousel
handle: gallery
maxAuthors: 1
name: Gallery
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  28873fc0-5092-43dc-94ff-c29ce0463c2c: # Sint Coleta
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  cbe9e6f0-0c8d-485f-b0d9-499af8215148: # Mariahuis
    enabledByDefault: true
    hasUrls: true
    template: _layouts/gallery.twig
    uriFormat: 'gallery/{slug}'
  f2fcfcef-2e85-4ee2-94c7-b1ce5abab2ac: # Cultuur Colette
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: 9cb0d407-6aeb-4294-a372-b1628dd6949e
type: structure
