defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: fc947245-56f3-40e9-bbd0-f927a5caa500 # logo
handle: logo
maxAuthors: 1
name: logo
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  28873fc0-5092-43dc-94ff-c29ce0463c2c: # Sint Coleta
    enabledByDefault: true
    hasUrls: true
    template: logo/_entry.twig
    uriFormat: 'logo/{slug}'
  cbe9e6f0-0c8d-485f-b0d9-499af8215148: # Mariahuis
    enabledByDefault: true
    hasUrls: true
    template: logo/_entry.twig
    uriFormat: 'logo/{slug}'
  f2fcfcef-2e85-4ee2-94c7-b1ce5abab2ac: # Cultuur Colette
    enabledByDefault: true
    hasUrls: true
    template: logo/_entry.twig
    uriFormat: 'logo/{slug}'
type: channel
