defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 4a263512-20cf-4cbe-9dda-a9705a47e161 # Navigation Link URL
  -
    uid: 370c7e06-ba86-44f6-9ebf-818f3cb54765 # Navigation Logo
handle: navigation
maxAuthors: 1
name: Navigation
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  cbe9e6f0-0c8d-485f-b0d9-499af8215148: # Mariahuis
    enabledByDefault: true
    hasUrls: true
    template: navigation/_entry.twig
    uriFormat: 'navigation/{slug}'
structure:
  maxLevels: null
  uid: 0b4fbb15-4b39-46af-be41-beeceee75932
type: structure
