defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 4a263512-20cf-4cbe-9dda-a9705a47e161 # Navigation Link URL
handle: navigation
maxAuthors: 1
name: Navigation
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  28873fc0-5092-43dc-94ff-c29ce0463c2c: # Sint Coleta
    enabledByDefault: true
    hasUrls: true
    template: navigation/_entry.twig
    uriFormat: 'navigation/{slug}'
  cbe9e6f0-0c8d-485f-b0d9-499af8215148: # Mariahuis
    enabledByDefault: true
    hasUrls: true
    template: navigation/_entry.twig
    uriFormat: 'navigation/{slug}'
  f2fcfcef-2e85-4ee2-94c7-b1ce5abab2ac: # Cultuur Colette
    enabledByDefault: true
    hasUrls: true
    template: navigation/_entry.twig
    uriFormat: 'navigation/{slug}'
structure:
  maxLevels: null
  uid: 0b4fbb15-4b39-46af-be41-beeceee75932
type: structure
