defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 264a95fa-2749-4b66-9b94-d40c2bd1d56b # woonpage
handle: woon
maxAuthors: 1
name: woon
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  cbe9e6f0-0c8d-485f-b0d9-499af8215148: # Mariahuis
    enabledByDefault: true
    hasUrls: true
    template: _layouts/woon.twig
    uriFormat: 'woon/{slug}'
structure:
  maxLevels: null
  uid: b6bfa039-0284-458b-a367-330b248d1038
type: structure
